### PR TITLE
Performance improvements

### PR DESCRIPTION
**Pull request by davidsj**
I made a few changes which yield improved performance, at least on my machine. With my GTX 980 Ti, I get about 40% higher throughput (~457 steps/sec vs. ~321 steps/sec), once exploration epsilon gets small. The main changes:
* _q_vals function uses a batch size of 1.
* _train function only has a single CPU-GPU roundtrip now, by doing terminal and action masking on the GPU.
* Before and after frames from replay memory share structure to minimize copying.

The learning behavior is *almost* identical: With --cudnn_deterministic=true, learning.csv initially shows values which are equivalent to all but the last few decimal places, the discrepancy probably due to a slight loss of floating point precision in parts. Eventually they diverge more fully since the agents start to acquire different experiences, but this takes a while.

Over about 50 epochs, learning behavior seems pretty similar. reward_per_episode compared (without --cudnn_deterministic in this case):
asterix
breakout
seaquest
space_invaders

And mean_q, from the same runs:

asterix
breakout
seaquest
space_invaders

### CODE REVIEW

**Comment by peterzcc** [comment]
Looks cool if the performance improves that much! Do we have any update on the results?

**Comment by davidsj** [comment]
I don't have any more results from this patch yet, but I'll do a few new runs starting tonight and post the results in a few days. I consider my observation about learning.csv the most relevant thing, since that suggests the learning behavior is identical up to floating point precision.

**Comment by davidsj** [comment]
Some data from six new runs to confirm that the learning behavior is quite similar.

### Reward per episode (master vs. qnet_perf)

asterix
breakout
gravitar
seaquest
space_invaders
tennis

### Mean Q (master vs. qnet_perf)

asterix
breakout
gravitar
seaquest
space_invaders
tennis

**Comment by davidsj** [comment]
Also, I got some performance numbers from a Kepler GPU, specifically an EC2 g2.2xlarge instance with a K520 GPU. On master, I get 122 steps/sec, vs. 204 steps/sec with qnet_perf. So this is about 67% faster in that case.

**Comment by spragunr** [comment]
This looks really good.  The speed improvements are definitely welcome.  I'll merge ASAP, but (as I seem to say a lot), I'm wrapped up with other responsibilities right now, so I won't be able to get to it immediately.  Have you looked at updating the existing unit tests to be consistent with these changes?

**Comment by davidsj** [comment]
Apologies for the delay and the oversight on unit tests.

I made three fixes to the unit tests:
* Fix incompatibility introduced in e84e80fc6a3125c95c9e5b41f39aa710ec71fae4 which caused input_scale to go from 1 to 255.
* Fix incompatibility introduced in 207247c622c9bb4353e87d34a98aa9c12f48be99 due to loss being halved.
* Update calls to net.train and net.q_vals based on the interface change in this pull request.

They all pass now.

**Pull request merged**
