### PR TITLE
Decoupling to promote reusability

### PR DESCRIPTION
**Pull request by jleni**
I know that it is a big PR but as already discussed, we can keep it here as a reference and discuss the details. The key idea is to decouple classes so it is possible to create alternative agents and experiments by composing/deriving from the main implementation.
There is a very simple example in run_random.py / ale_agent_random.py.
deep_q_rl could be used as a benchmark to compare new approaches, etc. without having to implement the whole infrastructure again.

### CODE REVIEW

**Comment by spragunr** [comment]
This looks great!  I see most of the changes as progress, and I'll try to make the time to get them into master. 

A couple of issues I see right away: 
* I think the q_network should maintain retain the choose_action method. 
* I prefer to keep line-lengths under 80. 

Since there are so many changes, I think the sane course is to create a dev branch for working on this. 

Would you be willing to: 
* create a new pull request targeted to the new dev branch?
*  (less importantly) address the two issues mentioned above?

**Comment by jleni** [comment]
Sure! I will change the settings in my IDE and review the code.

Regarding the q_network, the reason I did that is because I see the network as a q-estimator only. At the moment choose_action combines the q-estimation and the e-greedy exploration. Shouldn't the agent decide how to explore? 
In some cases, it might be interesting to use some different criteria to guide the exploration. This could be related or not to the network. I thought it was good if the network knew nothing about epsilons, etc.

In the end, it is not really important. It is always possible to leave it this way and access the q-values directly in custom implementations. 

It would be nice to see what you think, I am still learning about all this.

**Comment by spragunr** [comment]
You are right that the current distinction between the responsibilities of the ale_agent code and the q_network code are a little arbitrary.  I've tried to organize it so that the q_network code provides a complete q-learning implementation that is more or less independent of the ALE domain, while the ale_agent code captures the training and and data collection logic from the Nature paper.

**Comment by jleni** [comment]
No problem. Unfortunately, as far as I know, it is not possible to change the target branch in a PR.
We should close this one and open a new one.

I will target the dev branch but is it possible to rebase the dev branch to the latest master? 
I will fix the PEP8 problems and keep choose_action in the network as you asked.

**Comment by spragunr** [comment]
Done.

**Pull request closed without merging**
